### ISSUE TITLE
過濾問題

### ISSUE THREAD

**Issue by jkle112** [ilxp/luci-app-ikoolproxy#131]
前端路由器也具備過濾能力，加密過濾需要安裝數字證書，我替換了OPENWRT下的uhttpd.crt,uhttpd.key,也拷貝文件到系統配置下對應的個人證書文件夾下，但是IKOOLPROXY還是不支持，加密下載出問題，請問該如何解決，謝謝。

**Comment by ilxp** [comment]
110.110.110.110下载，一定要导入受信任的根目录！

**Comment by jkle112** [comment]
我知道是哪個文件，手動下載了，受信任的根目录是/root/目錄嗎？
我後來參照火狐瀏覽器導入的位置，放到了/etc/ssl/certs目錄下，請看看到底哪個更好？
