### ISSUE TITLE
极路由HiWiFi HC5962  MediaTek MT7621  ramips/mt7621，安装不了，提示未知软件包

### ISSUE THREAD

**Issue by lanyucomputer** [ilxp/luci-app-ikoolproxy#132]
安装不了，提示未知软件包，安装的是这两个包   [https://github.com/ilxp/luci-app-ikoolproxy/releases/download/v2022.10.11/koolproxy_3.8.5-1_mips_mips32.ipk]([https://github.com/ilxp/luci-app-ikoolproxy/releases/download/v2022.10.11/luci-app-ikoolproxy_3.8.5_all.ipk](url)，)

Unknown package 'luci-app-ikoolproxy'.

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency koolproxy for luci-app-ikoolproxy
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-ikoolproxy found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-ikoolproxy.

**Comment by lanyucomputer** [comment]
HiWiFi HC5962

内核版本 | 5.4.188

**Comment by lanyucomputer** [comment]
另外试了几个设备，一个玩客云5.9的内核，一个章鱼星球5.10.112-meson64-dev，可以安装上，但一直会停止运行，又正在运行，然后停止运行，重启的样子，都不能正常使用

**Comment by ilxp** [comment]
只支持5.4极其以下内核。

**Comment by lanyucomputer** [comment]
> 只支持5.4极其以下内核。

要怎么才可以支持高版本的内核呢，我试了很多的去广告，好像只有这个还有效，其它的都没有这个插件有效果，可惜的是，这个装上去之后不停的重启，有大神来修复升级吗？
