### ISSUE TITLE
最新版的k2p 编译后cpu一直100%

### ISSUE THREAD

**Issue by lm1618** [ilxp/luci-app-ikoolproxy#134]
最新版的k2p 编译后cpu一直100%，从老版本提取koolproxy文件替换后正常

**Comment by Karmylr** [comment]
日志呢

**Comment by dy2898** [comment]
newifi3同样遇到cpu100%,直接下载mipsel运行mipsel --help没有输出。用upx解压后可以正常运行，应该是压缩时出问题
