### ISSUE TITLE
听说 ikoolproxy  5.1 内核不支持，是吗？

### ISSUE THREAD

**Issue by qiang-yu** [ilxp/luci-app-ikoolproxy#135]
我刚试了 ikoolproxy，在 iPad 安装了 cert ，现在腾讯视频打开任何视频都是 “视频加载失败”，完全没法看视频了

全局模式 + 设定 iPad 的 mac 地址 + https 过滤

搜索了很久，就看到有人说 ikoolproxy 不支持 5.1 内核， 不知道是真是假，因为官方网页没有看到任何地方说不支持 5.1 内核，请教一下，谢谢

如果说不支持 5.1 内核， 那是要求内核 < 5.1 呢？ 还是要求内核 > 5.1 呢？

谢谢

**Comment by ilxp** [comment]
不支持5.10以上内核。用5.4内核吧

**Comment by lm1618** [comment]
K2p 使用5.10内核使用正常，k2p楼主的bin文件好像有问题，我从[其他地方](https://github.com/cnzd/luci-app-koolproxyR/tree/master/bin)下载的bin替换后可以使用

**Comment by b111110110** [comment]
mipsel 二制文件确实有问题，替换成 [lm1618](https://github.com/lm1618) 提供的bin文件解决了。
