### ISSUE TITLE
110.110.110.110 在以下版本下访问不了

### ISSUE THREAD

**Issue by kson34** [ilxp/luci-app-ikoolproxy#138]
110.110.110.110 在以下版本下访问不了
OpenWrt 11.19.2023 by Kiddin' / LuCI Master git-24.320.00560-0a9524d

log:

Wed Feb  7 12:30:42 2024 daemon.info koolproxy[21801]: listen socket on [0.0.0.0]:3000 success
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: koolproxy v3.8.6
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: listen port=3000
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: log level=4
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: thread count=4
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: work path=/
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: program path=/usr/share/koolproxy/koolproxy
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: data path=/usr/share/koolproxy/data
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: ttl mode=160
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: ttl port=0
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: mark mode=1
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: max fd=131070
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: init adblock engine
Wed Feb  7 12:30:47 2024 daemon.info koolproxy[21838]: load normal rule: /usr/share/koolproxy/data/rules/koolproxy.txt
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: load normal rule: /usr/share/koolproxy/data/rules/daily.txt
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: load secret rule: /usr/share/koolproxy/data/rules/kp.dat
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: WARN: load rule failed: /usr/share/koolproxy/data/rules/kp.dat
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: load normal rule: /usr/share/koolproxy/data/rules/user.txt
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: init https engine
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: https engine: load_key_file /usr/share/koolproxy/data/private/ca.key.pem failed: -1
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: init https engine failed:-2, go with http mode only
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: init proxy engine
Wed Feb  7 12:30:48 2024 daemon.info koolproxy[21838]: listen socket on [0.0.0.0]:3000 success

**Comment by lovexiaofan123** [comment]
在IOS端也用不了，即使装了证书并信任也不能访问被kp修改过的网址，替换了以前的内核就可以访问。

**Comment by ilxp** [comment]
openssl版本问题。需要降低到1.1才能下载证书。
