### ISSUE TITLE
問題反饋

### ISSUE THREAD

**Issue by jkle112** [ilxp/luci-app-ikoolproxy#140]
最新版本安裝到超過5.4的內核openwrt系統，運行不正常，雖然狀態顯示綠色，但是內存檢測，老是自動重啓，對網絡也造成影響，請檢查，期待更新，也期待盡可能多支持一些規則寫法

**Comment by ilxp** [comment]
openssl版本问题。目前只有lean大神的lede可以降低版本编译，并且运行完美。其余版本都不行。
