### ISSUE TITLE
在IOS下装上证书后并已经信任证书无法访问网址

### ISSUE THREAD

**Issue by lovexiaofan123** [ilxp/luci-app-ikoolproxy#141]
openssl已经是1.1版本了，110.110.110.110也能下载到证书。
也能运行二进制，但就是无法访问规则内修改后的的网址。直接提示浏览器无法访问网络，应该还是证书问题
替换以前的内核可以正常访问。
OP内核我现在是5.4
不知道更高的OP内核会不会有同样的情况出现。

**Comment by lovexiaofan123** [comment]
重新生成了证书可以了，把issues关了把

**Comment by SONGjiemo** [comment]
> 用新内核重新生成了证书后也还是不行，还是证书问题，在windows下装证书是正常的和https协议下都正常

这个插件如何安装呀，我路由器选择这个插件直接失败了
