### ISSUE TITLE
openwrt  安装插件  错误 255

### ISSUE THREAD

**Issue by SONGjiemo** [ilxp/luci-app-ikoolproxy#145]
![d1e88eec040da66a3b70066d1b1ed54b](https://github.com/ilxp/luci-app-ikoolproxy/assets/46627639/7ec0d3ea-a1c7-4c04-8800-98525de9e082)
如图所示，不知道为什么会报错。
希望可以指点我一下。
![image](https://github.com/ilxp/luci-app-ikoolproxy/assets/46627639/fa739160-5e97-4794-999d-f96ca9bab921)

**Comment by ilxp** [comment]
随固件编译

**Comment by SONGjiemo** [comment]
> 随固件编译

如何随固件编译呀，这个插件需要多大空间呀
