### ISSUE TITLE
黑白名单有其他实现方式吗

### ISSUE THREAD

**Issue by lnc1995** [ilxp/luci-app-ikoolproxy#146]
我真是吐血了，昨晚刚研究好打包成Docker…今天就更新了…
我看源码里面用iptables和ipset实现的黑白名单，Docker环境下，有的内核里面没有相关模块，主功能倒是不影响，但是用到这俩的功能都不行

**Comment by lnc1995** [comment]
以及说明中提到ipset需要版本6。我看OP的分支，22.X的openssl还是1.1版本，到23.X就是3.0版本了。最新的更新解决了openssl的适配，拿23.X编译的话，ipset版本就是7.X了，会出现问题吗

**Comment by ilxp** [comment]
有两个分支，ssl1分支是openssl1.x的。期待的打包成docker。

**Comment by lnc1995** [comment]
> 有两个分支，ssl1分支是openssl1.x的。期待的打包成docker。

ipset呢，如果拿ssl3的去编译，ipset就是7.X版本了，这个有问题吗
