### ISSUE TITLE
这个规则能转换使用吗？

### ISSUE THREAD

**Issue by lnc1995** [ilxp/luci-app-ikoolproxy#147]
https://bitbucket.org/hacamer/adrules/raw/main/adblock.txt
[这个网站](https://adblock-tester.com/)测试下来，上面的规则可以做到全屏蔽，现有的规则还有些遗漏

**Comment by SONGjiemo** [comment]
> https://bitbucket.org/hacamer/adrules/raw/main/adblock.txt [这个网站](https://adblock-tester.com/)测试下来，上面的规则可以做到全屏蔽，现有的规则还有些遗漏

这就插件你是如何安装的，为什么我不能成功呀。需要多大空间呀

**Comment by lnc1995** [comment]
> > https://bitbucket.org/hacamer/adrules/raw/main/adblock.txt [这个网站](https://adblock-tester.com/)测试下来，上面的规则可以做到全屏蔽，现有的规则还有些遗漏
> 
> 这就插件你是如何安装的，为什么我不能成功呀。需要多大空间呀

大概4MB就可以安装，但是规则还得占用空间，给个10MB稳妥一些

**Comment by lnc1995** [comment]
好吧，不用了，我自己测试了下，可以转换，也能加载，但是对效果没提升。选个ADG和ANTI规则就行了…
