### ISSUE TITLE
可以帮忙弄一下预编译包吗

### ISSUE THREAD

**Issue by f0re1gnKey** [ilxp/luci-app-ikoolproxy#148]
release里预编译包好像都没有了，可以帮忙弄一下预编译包吗

**Comment by ilxp** [comment]
已经编译好

**Comment by f0re1gnKey** [comment]
[arm_cortex-a7](https://github.com/ilxp/luci-app-ikoolproxy/actions/runs/9509810142/artifacts/1600601006)

请教如何查找其他架构的ipks，只发现了a7的
